Repository danger-ahead/roBOT, pull requests merged in 2021-10, with the labels that each got.

#77 Contributing.md added
  CONTRIBUTING.MD
Labels: hactoberfest-accepted

#83 Webpages
  pages/command.html
  pages/css/command.css
  pages/css/command.css.map
  pages/css/command.scss
  pages/css/style.css
  pages/images/bg-mob.jpg
  pages/images/bg.jpg
  pages/images/bg.png
  pages/index.html
  pages/js/misc.js
  pages/js/resp.js
  pages/query.html
Labels: hacktoberfest-accepted

#80 Update ISSUE Template
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/feature.yaml
Labels: hacktoberfest-accepted

#88 #Resolved 86 Added Compliment command
  commands/__init__.py
  commands/compliment.py
  commands/help.py
  commands/hi_contrib.py
  main.py
Labels: hacktoberfest-accepted

#90 #Resolved 89 Updating documentation part
  commands/help.py
  docs/COMMANDS.md
Labels: hacktoberfest-accepted

#97 Development
  .env.example
  .gitignore
  command/database/confess.py
  command/database/loader/database.py
  command/database/loader/loader.py
  command/database/rank.py
  command/scripts/moderate_words.txt
Labels: hacktoberfest-accepted, project restructure

#99 added slowmode command
  command/general/slomode.py
  docs/COMMANDS.md
Labels: enhancement, hacktoberfest-accepted, project restructure

#101 Google Search Command
  command/general/reddit.py
  command/general/search.py
  command/general/slowmode.py
  requirements.txt
Labels: enhancement, hacktoberfest-accepted, project restructure

#102 Wikipedia search command
  command/general/wikipedia.py
  requirements.txt
Labels: enhancement, hacktoberfest-accepted, project restructure

#106 Checks, Fixed Reddit & small fixes.
  .env.example
  .gitignore
  command/database/admin_configure.py
  command/database/admin_deconfigure.py
  command/general/reddit.py
  requirements.txt
Labels: hacktoberfest-accepted, project restructure

#104 Pokedex Command
  command/api/pokemon.py
  docs/DEPENDENCIES.md
Labels: enhancement, hacktoberfest-accepted, project restructure

#108 changed from requests to aiohttp
  command/api/pokemon.py
  command/general/f.py
  command/general/ptrivia.py
  command/general/song.py
  command/general/trivia.py
  command/general/wea.py
Labels: hacktoberfest-accepted
